from firewall.newSSH import sshSession
import ipaddress


def ncviBaseConfig(fwIP, hostname):

    baseConfig = [
        'clish -c "set user admin shell /bin/bash"',
        'clish -c "set inactivity-timeout 60"',
        'clish -c "set web session-timeout 10"',
        'echo "Y" | clish -c "set web ssl-port 1218"',  # Need to figure out how to handle Y/N prompt
        'clish -c "set web daemon-enable on"',
        'clish -c "set net-access telnet off"',
        'clish -c "set core-dump enable"',
        'clish -c "set core-dump total 1000"',
        'clish -c "set core-dump per_process 2"',
        'clish -c "set ipv6-state off"',
        'clish -c "add allowed-client host any-host"',
        'clish -c "set arp table cache-size 1024"',
        'clish -c "set arp table validity-timeout 60"',
        'clish -c "set net-access telnet off"',
        'clish -c "set snmp mode default"',
        'clish -c "set snmp agent on"',
        'clish -c "set snmp agent-version any"',
        'clish -c "set snmp community cpcontrol read-only"',
        'clish -c "set snmp community cpcontrol read-write"',
        'clish -c "add snmp interface Mgmt"',
        'clish -c "set snmp contact \"NOC\""',
        'clish -c "set snmp location \"{}\"'.format(hostname),
        'clish -c "add snmp custom-trap chkpntCPUCoreUtilTrap oid .1.3.6.1.4.1.2620.1.2000.3.1 operator Greater_Than threshold \\"90\\" frequency 300 message \\"High CPU Core Utilization\\""',
        'clish -c "add snmp custom-trap chkpntDiskSpaceTrap oid .1.3.6.1.4.1.2620.1.2000.2.6.1 operator Changed threshold \\"change\\" frequency 300 message \\"Low Disk Space\\""',
        'clish -c "add snmp custom-trap chkpntFanSpeedTrap oid .1.3.6.1.4.1.2620.1.3000.5.2.1 operator Changed threshold \\"change\\" frequency 600 message \\"Device Fan Failure\\""',
        'clish -c "add snmp custom-trap chkpntPowerSupplyTrap oid .1.3.6.1.4.1.2620.1.3000.5.4.1 operator Changed threshold \\"change\\" frequency 600 message \\"Power Supply Alert\\""',
        'clish -c "add snmp custom-trap chkpntRealMemoryTrap oid .1.3.6.1.4.1.2620.1.2000.4.2 operator Greater_Than threshold \\"70\\" frequency 300 message \\"Real Memory Utilization above 70% Threshold\\""',
        'clish -c "add snmp custom-trap chkpntSwapMemoryTrap oid .1.3.6.1.4.1.2620.1.2000.4.1 operator Greater_Than threshold \\"70\\" frequency 300 message \\"Swap Memory Utilization above 70% Threshold\\""',
        'clish -c "add snmp custom-trap chkpntTempertureTrap oid .1.3.6.1.4.1.2620.1.3000.5.1.1 operator Changed threshold \\"change\\" frequency 600 message \\"High Operating Temperature Alert\\""',
        'clish -c "add snmp custom-trap chkpntTrapBytesThroughput oid .1.3.6.1.4.1.2620.1.2000.1.5 operator Greater_Than threshold \\"500000\\" frequency 300 message \\"Throughput Exceeded Threshold\\""',
        'clish -c "add snmp custom-trap chkpntTrapLSConnState oid .1.3.6.1.4.1.2620.1.2000.7.1 operator Changed threshold \\"change\\" frequency 300 message \\"Connection Status to Log Server Changed\\""',
        'clish -c "add snmp custom-trap chkpntTrapNetIfUnplugged oid .1.3.6.1.4.1.2620.1.2000.1.2 operator Changed threshold \\"change\\" frequency 300 message \\"Interface Removed From Connection Table\\""',
        'clish -c "add snmp custom-trap fwNumConn oid .1.3.6.1.4.1.2620.1.1.25.3 operator Greater_Than threshold \\"300000\\" frequency 300 message \\"Concurrent Connection Threshold Exceeded\\""',
        'clish -c "add snmp custom-trap haState oid .1.3.6.1.4.1.2620.1.5.6 operator Changed threshold \\"change\\" frequency 300 message \\"Firewall HA Status Changed\\""',
        'clish -c "add aaa radius-servers priority 0 host 10.27.21.99 port 1812 secret fYiqjiaw timeout 5"',
        'clish -c "add aaa radius-servers priority 1 host 10.90.42.49 port 1812 secret fYiqjiaw timeout 5"',
        'clish -c "set snmp agent on"',
        'clish -c "set snmp agent-version any"',
        'clish -c "set snmp community eiQrd6Wv read-only"',
        'clish -c "set snmp community d6nuPDTy read-write"',
        'clish -c "add user corpsvcpatrolexp uid 0 homedir /home/ccorpsvcpatrolexp"',
        'clish -c "add rba user corpsvcpatrolexp roles monitorRole"',
        'clish -c "set user corpsvcpatrolexp shell /bin/bash"',
        'clish -c "add user chkptmonitor uid 0 homedir /home/chkptmonitor"',
        'clish -c "add rba user chkptmonitor roles adminRole"',
        'clish -c "set user chkptmonitor gid 0 shell /bin/bash"',
        'clish -c "add user nkt2523 uid 0 homedir /home/nkt2523"',
        'clish -c "add rba user nkt2523 roles adminRole"',
        'clish -c "set user nkt2523 shell /bin/bash"',
        'clish -c "add user nhy2569 uid 0 homedir /home/nhy2569"',
        'clish -c "add rba user nhy2569 roles adminRole"',
        'clish -c "set user nhy2569 shell /bin/bash"',
        'clish -c "add user ngu8369 uid 0 homedir /home/ngu8369"',
        'clish -c "add rba user ngu8369 roles adminRole"',
        'clish -c "set user ngu8369 shell /bin/bash"',
        'clish -c "add user ydm1817 uid 0 homedir /home/ydm1817"',
        'clish -c "add rba user ydm1817 roles adminRole"',
        'clish -c "set user ydm1817 shell /bin/bash"',
        'clish -c "add user qhp5971 uid 0 homedir /home/qhp5971"',
        'clish -c "add rba user qhp5971 roles adminRole"',
        'clish -c "set user qhp5971 shell /bin/bash"',
        'clish -c "add user exx9622 uid 0 homedir /home/exx9622"',
        'clish -c "add rba user exx9622 roles adminRole"',
        'clish -c "set user exx9622 shell /bin/bash"',
        'clish -c "add user clo8745 uid 0 homedir /home/clo8745"',
        'clish -c "add rba user clo8745 roles adminRole"',
        'clish -c "set user clo8745 shell /bin/bash"',
        'clish -c "add user tfn9845 uid 0 homedir /home/tfn9845"',
        'clish -c "add rba user tfn9845 roles adminRole"',
        'clish -c "set user tfn9845 shell /bin/bash"',
        'clish -c "add user jxu8356 uid 0 homedir /home/jxu8356"',
        'clish -c "add rba user jxu8356 roles adminRole"',
        'clish -c "set user jxu8356 shell /bin/bash"',
        'clish -c "add user yzg0685 uid 0 homedir /home/yzg0685"',
        'clish -c "add rba user yzg0685 roles adminRole"',
        'clish -c "set user yzg0685 shell /bin/bash"',
        'clish -c "add user zcn2862 uid 0 homedir /home/zcn2862"',
        'clish -c "add rba user zcn2862 roles adminRole"',
        'clish -c "set user zcn2862 shell /bin/bash"',
        'clish -c "add user qem8550 uid 0 homedir /home/qem8550"',
        'clish -c "add rba user qem8550 roles adminRole"',
        'clish -c "set user qem8550 shell /bin/bash"',
        'clish -c "add user kwb7577 uid 0 homedir /home/kwb7577"',
        'clish -c "add rba user kwb7577 roles adminRole"',
        'clish -c "set user kwb7577 shell /bin/bash"',
        'clish -c "add user nws9278 uid 0 homedir /home/nws9278"',
        'clish -c "add rba user nws9278 roles adminRole"',
        'clish -c "set user nws9278 shell /bin/bash"',
        'clish -c "add user ftq4622 uid 0 homedir /home/ftq4622"',
        'clish -c "add rba user ftq4622 roles adminRole"',
        'clish -c "set user ftq4622 shell /bin/bash"',
        'clish -c "add user hla8983 uid 0 homedir /home/hla8983"',
        'clish -c "add rba user hla8983 roles adminRole"',
        'clish -c "set user hla8983 shell /bin/bash"',
        'clish -c "add user dge7132 uid 0 homedir /home/dge7132"',
        'clish -c "add rba user dge7132 roles adminRole"',
        'clish -c "set user dge7132 shell /bin/bash"',
        'clish -c "add user dsx9873 uid 0 homedir /home/dsx9873"',
        'clish -c "add rba user dsx9873 roles adminRole"',
        'clish -c "set user dsx9873 shell /bin/bash"',
        'clish -c "add user qph0485 uid 0 homedir /home/qph0485"',
        'clish -c "add rba user qph0485 roles adminRole"',
        'clish -c "set user qph0485 shell /bin/bash"',
        'clish -c "add user idp9922 uid 0 homedir /home/idp9922"',
        'clish -c "add rba user idp9922 roles adminRole"',
        'clish -c "set user idp9922 shell /bin/bash"',
        'clish -c "add user ojl8634 uid 0 homedir /home/ojl8634"',
        'clish -c "add rba user ojl8634 roles adminRole"',
        'clish -c "set user ojl8634 shell /bin/bash"',
        'clish -c "add user csl2684 uid 0 homedir /home/csl2684"',
        'clish -c "add rba user csl2684 roles adminRole"',
        'clish -c "set user csl2684 shell /bin/bash"',
        'clish -c "add user cij8153 uid 0 homedir /home/cij8153 "',
        'clish -c "add rba user cij8153  roles adminRole"',
        'clish -c "set user cij8153  shell /bin/bash"',
        'clish -c "add user cco7478 uid 0 homedir /home/cco7478 "',
        'clish -c "add rba user cco7478  roles adminRole"',
        'clish -c "set user cco7478  shell /bin/bash"',
        'clish -c "add user lke7829 uid 0 homedir /home/lke7829"',
        'clish -c "add rba user lke7829 roles adminRole"',
        'clish -c "set user lke7829 shell /bin/bash"',
        'clish -c "add user nhe8441 uid 0 homedir /home/nhe8441"',
        'clish -c "add rba user nhe8441 roles adminRole"',
        'clish -c "set user nhe8441 shell /bin/bash"',
        'clish -c "add user cpv2536 uid 0 homedir /home/cpv2536"',
        'clish -c "add rba user cpv2536 roles adminRole"',
        'clish -c "set user cpv2536 shell /bin/bash"',
        'clish -c "add user mhu8789 uid 0 homedir /home/mhu8789"',
        'clish -c "add rba user mhu8789 roles adminRole"',
        'clish -c "set user mhu8789 shell /bin/bash"',
        'clish -c "add user dwo7956 uid 0 homedir /home/dwo7956"',
        'clish -c "add rba user dwo7956 roles adminRole"',
        'clish -c "set user dwo7956 shell /bin/bash"',
        'clish -c "add user kfa7950 uid 0 homedir /home/kfa7950"',
        'clish -c "add rba user kfa7950 roles adminRole"',
        'clish -c "set user kfa7950 shell /bin/bash"',
        'clish -c "add user IYK7384 uid 0 homedir /home/IYK7384"',
        'clish -c "add rba user IYK7384 roles adminRole"',
        'clish -c "set user IYK7384 shell /bin/bash"',
        'clish -c "add user RCU7449 uid 0 homedir /home/RCU7449"',
        'clish -c "add rba user RCU7449 roles adminRole"',
        'clish -c "set user RCU7449 shell /bin/bash"',
        'clish -c "add user jio8690 uid 0 homedir /home/jio8690"',
        'clish -c "add rba user jio8690 roles adminRole"',
        'clish -c "set user jio8690 shell /bin/bash"',
        'clish -c "add user ENG9850 uid 0 homedir /home/ENG9850"',
        'clish -c "add rba user ENG9850 roles adminRole"',
        'clish -c "set user ENG9850 shell /bin/bash"',
        'clish -c "add user fob8572 uid 0 homedir /home/fob8572"',
        'clish -c "add rba user fob8572 roles adminRole"',
        'clish -c "set user fob8572 shell /bin/bash"',
        'clish -c "save config"',
    ]

    if bool(ipaddress.IPv4Address(fwIP)) is False:
        return 'IP address provided is invalid'

    ssh = sshSession(fwIP, 'admin', 'hc@3c11')
    for command in baseConfig:
        print(command)
        output = ssh.executeCmd(command)
        print(output)
    # print(output)
    ssh.ssh.close()

    return 'Base Config sent to {}'.format(fwIP)
