name: Container Image Build

on:
  # schedule:
  #   - cron: "0 0 1 2,5,8,11 *"

  # push:
    # tags:
    #   - "*"
    # branches:
    #   - main

  pull_request:
    branches:
      - main
    types:
      - closed

  workflow_dispatch:
    description: "Logging level"
    required: true
    default: "warning"
    type: choice
    options:
      - error
      - warning
      - info
      - debug

jobs:
  # See the below URL reference for information regarding the parameters
  # available for the ru-container-image-build reusable workflow.
  # https://github.com/HCACPA/.github/blob/main/docs/ru-container-image-build.md
  build-image:
    if: github.repository != 'HCACPA/base-container-image-build-template'
    uses: HCACPA/.github/.github/workflows/ru-container-image-build.yml@v1.1.6
    secrets:
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      wiz-client-id: ${{ secrets.WIZ_CLIENT_ID }}
      wiz-client-secret: ${{ secrets.WIZ_CLIENT_SECRET }}
      docker-secrets: |
        NEXUSUSER=${{ secrets.REGISTRY_USERNAME }}
        NEXUSPASS=${{ secrets.REGISTRY_PASSWORD }}

    with:
      run-build-test: false
      action-runner-list: '["onprem-k8s-arc","lnx-amd64","enterprise","dind","self-hosted"]'
      alternate-image-tag: "latest"
      create-release: false
      image-name: "pyapis-prd"
      registry: "hcanetworkservicesdocker.repos.medcity.net"
