name: Changelog

on:
  pull_request:
    types: [closed]
  release:
    types: [published]
  issues:
    types: [closed, edited]
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for main branch
    steps:
      - uses: actions/checkout@v3
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          #token: ${{ secrets.YOUR_GITHUB_TOKEN or GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: "main"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name:  "$(git log -n 1 --pretty=format:%an)"
          author_email: "$(git log -n 1 --pretty=format:%ae)" 
          message: "Updated CHANGELOG.md"
          add: 'CHANGELOG.md'
