name: Container Image Build (Nightly)

on:
  schedule:
    - cron: "0 0 * * SUN-FRI"
  workflow_dispatch:
    description: "Logging level"
    required: true
    default: "warning"
    type: choice
    options:
      - error
      - warning
      - info
      - debug

jobs:
  # See the below URL reference for information regarding the parameters
  # available for the ru-container-image-build reusable workflow.
  # https://github.com/HCACPA/.github/blob/main/docs/ru-container-image-build.md
  build-image:
    if: github.repository != 'HCACPA/base-container-image-build-template'
    uses: HCACPA/.github/.github/workflows/ru-container-image-build.yml@v1.0.10
    secrets:
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      wiz-client-id: ${{ secrets.WIZ_CLIENT_ID }}
      wiz-client-secret: ${{ secrets.WIZ_CLIENT_SECRET }}
    with:
      action-runner-list: '["onprem-k8s-arc","lnx-amd64","enterprise","dind","self-hosted"]'
      alternate-image-tag: "nightly"
      create-release: false
      image-name: "REQD_IMAGE_REGISTRY_BASE_PATH/REQD_IMAGE_NAME"
      registry: "REQD_IMAGE_REGISTRY_URL"
